In [62]:
import numpy as np

In [63]:
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])  # y[::2] : step 2
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [70]:
y = np.zeros(100)
np.power(2,np.arange(1,101,2,dtype='uint64'),out=y[::2])
y = y.astype(np.uint64)


In [72]:
y = np.zeros(100)
np.add(2,np.arange(1,101,2),out=y[::2])
y = y.astype(np.uint64)
y

array([  3,   0,   5,   0,   7,   0,   9,   0,  11,   0,  13,   0,  15,
         0,  17,   0,  19,   0,  21,   0,  23,   0,  25,   0,  27,   0,
        29,   0,  31,   0,  33,   0,  35,   0,  37,   0,  39,   0,  41,
         0,  43,   0,  45,   0,  47,   0,  49,   0,  51,   0,  53,   0,
        55,   0,  57,   0,  59,   0,  61,   0,  63,   0,  65,   0,  67,
         0,  69,   0,  71,   0,  73,   0,  75,   0,  77,   0,  79,   0,
        81,   0,  83,   0,  85,   0,  87,   0,  89,   0,  91,   0,  93,
         0,  95,   0,  97,   0,  99,   0, 101,   0], dtype=uint64)

In [73]:
x=np.arange(1,6)

In [81]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
x = np.random.normal(0,1,1000)
np.sum((x>0.5) & (x<0.7))

71

In [102]:
np.random.seed(10)
x = np.random.randint(1,100,200)
x[x>x.mean()] + x.std().round(2)

array([ 95.06, 120.06, 124.06, 104.06,  85.06, 119.06,  93.06, 103.06,
       109.06,  82.06,  85.06, 108.06, 100.06, 123.06, 117.06, 120.06,
        96.06,  88.06, 124.06, 108.06, 125.06, 105.06, 119.06, 111.06,
       102.06, 119.06, 106.06, 115.06, 127.06, 119.06, 102.06, 119.06,
       119.06,  81.06,  85.06, 108.06, 119.06, 116.06, 123.06, 127.06,
        93.06,  88.06, 110.06,  88.06, 128.06,  81.06, 120.06, 104.06,
       115.06, 113.06,  82.06, 110.06,  81.06,  84.06, 112.06, 111.06,
       121.06, 112.06, 104.06,  95.06, 127.06,  97.06,  98.06,  93.06,
       126.06, 113.06,  93.06, 108.06, 124.06, 106.06, 117.06, 126.06,
       119.06, 127.06, 104.06, 121.06, 102.06, 116.06, 103.06, 120.06,
       109.06, 112.06, 116.06,  93.06, 118.06, 125.06, 122.06,  83.06,
       107.06,  99.06, 101.06, 105.06,  96.06, 106.06,  83.06, 124.06,
       115.06,  93.06])

In [124]:
x = np.array([2,1,3,4,5])
np.sort(x)[::-1]
i = np.argsort(x)
x[i]
rand = np.random.RandomState(42)
X = rand.randint(0,10,(4,6))
print(X)
np.sort(X,axis=0)
np.partition(x,4)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([1, 2, 3, 4, 5])

In [143]:
np.random.seed(10)
x = np.random.randint(1,100,100)
print(x.mean())
x

49.24


array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1, 41, 37, 17, 12, 55, 89, 63,
       34, 73, 79, 50, 52, 55, 78, 70, 14, 26, 14, 93, 87, 31, 31, 90, 13,
       66, 32, 58, 37, 28, 19, 94, 78, 23, 24, 95, 12, 29, 75, 89, 10, 16,
       19, 81, 72, 89, 12, 18, 47,  8, 76, 29, 34, 85, 97, 89, 45,  6,  5,
       72, 89, 89, 51, 55, 35, 16, 78, 89, 16,  7, 86, 23, 12, 13, 93, 97,
       63, 58, 80, 43, 58, 98, 51, 46, 41, 90, 74, 38,  1, 19, 24])